################################################################
# Global configuration
################################################################
debug = true
logLevel = "DEBUG"

################################################################
# Entrypoints configuration
################################################################
[entryPoints]
    [entryPoints.http]
    address = ":80"

################################################################
# API and dashboard configuration
################################################################
[api]
    entryPoint = "traefik"
    dashboard = true

################################################################
# Consul Catalog
################################################################
[consulCatalog]
endpoint = "127.0.0.1:8500"
exposedByDefault = false
prefix = "traefik"
domain = "localhost"