hello_word="Hello Word. Mensagem de teste."
hello_word_param="Hello Word. Mensagem de teste {{.Name}}."
login10="Login de usuário vazio, inválido para cadastro."
login20="Senha de usuário vazio, inválido para cadastro."
login30="Email do usuário vazio ou inválido."
logincompany10="Login de usuário vazio, inválido para cadastro."
logincompany20="Senha de usuário vazio, inválido para cadastro."
logincompany30="Companhia associada ao login, inválida."
logincompany40="Email do usuário vazio ou inválido."
company10="Nome companhia vazia, inválida para cadastro."
profile10="Nome perfil vazio, inválido para cadastro."
profile20="Lista de permissões associada ao perfil vazia, inválida para registro."
profilecompany10="Empresa associada ao perfil não é válido, inválido para registro."
routine10="Caminho da rotina vazio, inválido para registro."
routine20="Nome da rotina vazio, inválido para registro."
permission10="Erro ao criar permissão, ao menos uma permissão(criar, ler, atualizar ou deletar) deve ser concedida."