CREATE SEQUENCE IF NOT EXISTS COMPANY_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS COMPANY
(
    ID        BIGINT DEFAULT NEXTVAL('COMPANY_ID_SEQ') PRIMARY KEY,
    VERSION   INTEGER      NOT NULL,
    UUID_CODE UUID   DEFAULT UUID_GENERATE_V4(),
    NAME      VARCHAR(200) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS LOGIN_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE IF NOT EXISTS LOGIN
(
    ID       BIGINT DEFAULT NEXTVAL('LOGIN_ID_SEQ') PRIMARY KEY,
    VERSION  INTEGER      NOT NULL,
    LOGIN    VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(64)  NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS LOGIN_COMPANY_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE IF NOT EXISTS LOGIN
(
    ID         BIGINT DEFAULT NEXTVAL('LOGIN_COMPANY_ID_SEQ') PRIMARY KEY,
    VERSION    INTEGER      NOT NULL,
    LOGIN      VARCHAR(200) NOT NULL,
    PASSWORD   VARCHAR(64)  NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    ID_COMPANY BIGINT       NOT NULL,
    CONSTRAINT LOGIN_COMPANY_COMPANY FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY (ID)
);

CREATE SEQUENCE IF NOT EXISTS ROUTINE_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE IF NOT EXISTS ROUTINE
(
    ID          BIGINT DEFAULT NEXTVAL('ROUTINE_ID_SEQ') PRIMARY KEY,
    VERSION     INTEGER      NOT NULL,
    PATH        VARCHAR(100) NOT NULL,
    ROTINE_NAME VARCHAR(100) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS PROFILE_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE IF NOT EXISTS PROFILE
(
    ID      BIGINT DEFAULT NEXTVAL('PROFILE_ID_SEQ') PRIMARY KEY,
    VERSION INTEGER      NOT NULL,
    NAME    VARCHAR(200) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS PROFILE_COMPANY_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE IF NOT EXISTS PROFILE_COMPANY
(
    ID         BIGINT DEFAULT NEXTVAL('PROFILE_COMPANY_ID_SEQ') PRIMARY KEY,
    VERSION    INTEGER      NOT NULL,
    NAME       VARCHAR(200) NOT NULL,
    ID_COMPANY BIGINT       NOT NULL,
    CONSTRAINT PROFILE_COMPANY_COPANY FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY (ID)
);

CREATE SEQUENCE IF NOT EXISTS PERMISSION_ID_SEQ
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE IF NOT EXISTS PERMISSION
(
    ID                 BIGINT           DEFAULT NEXTVAL('PERMISSION_ID_SEQ') PRIMARY KEY,
    VERSION            INTEGER NOT NULL,
    ID_ROUTINE         BIGINT  NOT NULL,
    TO_CREATE          BOOLEAN NOT NULL DEFAULT FALSE,
    TO_READ            BOOLEAN NOT NULL DEFAULT FALSE,
    TO_UPDATE          BOOLEAN NOT NULL DEFAULT FALSE,
    TO_DELETE          BOOLEAN NOT NULL DEFAULT FALSE,
    ID_PROFILE         BIGINT,
    ID_PROFILE_COMPANY BIGINT,
    CONSTRAINT PERMISSION_ROUTINE FOREIGN KEY (ID_ROUTINE) REFERENCES ROUTINE (ID),
    CONSTRAINT PERMISSION_PROFILE FOREIGN KEY (ID_PROFILE) REFERENCES PROFILE (ID),
    CONSTRAINT PERMISSION_PROFILE_COMPANY FOREIGN KEY (ID_PROFILE_COMPANY) REFERENCES PROFILE_COMPANY (ID)
);