hello_word="Hello Word. Test message."
hello_word_param="Hello Word. Test message {{.Name}}."
login10="Empty user login, invalid for registration."
login20="Empty user password, invalid for registration."
login30="Email user empty or invalid."
logincompany10="Empty user login, invalid for registration."
logincompany20="Empty user password, invalid for registration."
logincompany30="Company associated with login, invalid."
logincompany40="Email user empty or invalid."
company10="Empty company name, invalid for registration."
profile10="Empty profile name, invalid for registration."
profile20="Permission list associated in profile empty, invalid for registration."
profilecompany10="Company associated the profile is not valid, invalid to registration."
routine10="Empty routine path, invalid for registration."
routine20="Empty routine name, invalid for registration."
permission10="Error creating permission, at least one permission (create, read, update or delete) must be granted."